name: Test
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -name: Clone repository
        uses: actions/checkout@v6
      -name: Install Node
        uses: actions/setup-node@v6 
        with:
          node-version: 20
        -name: Node version 
          run: node -v
        -name: Install dependencies
          run: npm ci
        -name: Test
          run: npm test